;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"

NumBitsForContainerSize=6
NetIndexFirstBitSegment=16


+GameplayTagList=(Tag="Character",DevComment="캐릭터")
+GameplayTagList=(Tag="Character.State",DevComment="")
+GameplayTagList=(Tag="Character.State.NotAttackable",DevComment="")
+GameplayTagList=(Tag="Character.State.NotMoveable",DevComment="")
+GameplayTagList=(Tag="Character.State.NotRollable",DevComment="")
+GameplayTagList=(Tag="Character.State.PressedAttack",DevComment="")
+GameplayTagList=(Tag="Character.State.Death",DevComment="")

+GameplayTagList=(Tag="Character.Buff",DevComment="")
+GameplayTagList=(Tag="Character.Buff.FastAttackSpeed",DevComment="캐릭터 공격속도 증가버프")
+GameplayTagList=(Tag="Character.Buff.Heal",DevComment="")

+GameplayTagList=(Tag="Character.DeBuff",DevComment="")
+GameplayTagList=(Tag="Character.DeBuff.Stunned",DevComment="")
+GameplayTagList=(Tag="Character.DeBuff.Poison",DevComment="")
+GameplayTagList=(Tag="Character.DeBuff.Burn",DevComment="")
+GameplayTagList=(Tag="Character.DeBuff.Slow",DevComment="")


+GameplayTagList=(Tag="Enemy",DevComment="")
+GameplayTagList=(Tag="Enemy.State",DevComment="")
+GameplayTagList=(Tag="Enemy.State.Strafing",DevComment="")

+GameplayTagList=(Tag="Enemy.Buff",DevComment="")

+GameplayTagList=(Tag="Enemy.DeBuff",DevComment="")
+GameplayTagList=(Tag="Enemy.Debuff.Damage.Burn",DevComment="")
+GameplayTagList=(Tag="Enemy.Debuff.Locomotion",DevComment="")
+GameplayTagList=(Tag="Enemy.Debuff.Locomotion.KnockBack",DevComment="")
+GameplayTagList=(Tag="Enemy.Debuff.Locomotion.Stunned",DevComment="")






