;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Character.Status",NewTagName="Character.State")
+GameplayTagRedirects=(OldTagName="Character.State.Buff",NewTagName="Character.Buff")
+GameplayTagRedirects=(OldTagName="Character.State.Debuff",NewTagName="Character.Debuff")
+GameplayTagRedirects=(OldTagName="Monster.Debuff",NewTagName="Monster.State.Debuff")
+GameplayTagRedirects=(OldTagName="Character.Buff.IncreasedAttackSpeed",NewTagName="Character.Buff.FastAttackSpeed")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character",DevComment="캐릭터")
+GameplayTagList=(Tag="Character.Buff",DevComment="")
+GameplayTagList=(Tag="Character.Buff.FastAttackSpeed",DevComment="캐릭터 공격속도 증가버프")
+GameplayTagList=(Tag="Character.Debuff",DevComment="")
+GameplayTagList=(Tag="Character.Debuff.Stunned",DevComment="")
+GameplayTagList=(Tag="Character.State",DevComment="")
+GameplayTagList=(Tag="Character.State.Attackable",DevComment="")
+GameplayTagList=(Tag="Character.State.Moveable",DevComment="")
+GameplayTagList=(Tag="Character.State.MoveAttackable",DevComment="")
+GameplayTagList=(Tag="Monster",DevComment="")
+GameplayTagList=(Tag="Monster.Debuff.Damage.Burn",DevComment="")
+GameplayTagList=(Tag="Monster.Debuff.Locomotion",DevComment="")
+GameplayTagList=(Tag="Monster.Debuff.Locomotion.KnockBack",DevComment="")
+GameplayTagList=(Tag="Monster.Debuff.Locomotion.Stunned",DevComment="")
+GameplayTagList=(Tag="Monster.State",DevComment="")
+GameplayTagList=(Tag="Monster.State.Strafing",DevComment="")

